// Seed data for the Operational Hazard Register, extracted one-time from the
// "Cranfield Glass Operational Hazard Register" spreadsheet (v1, updated 26/06/2026).
// The app database is the live register from here on - this file only feeds the
// initial run-once startup migration and is never re-read after that.

export interface HazardSeed {
  hazardId: string;
  category: string;
  riskHarm: string;
  initialRisk: string;
  controlType: string;
  controls: string;
  residualRisk: string;
  reviewTrigger: string;
  nextReview: string;
  training: string;
  aroflowGroup: string;
  identified: string;
}

export const HAZARD_REGISTER_SEED: HazardSeed[] = [
  {
    hazardId: "CG-HZ-001A",
    category: "Glass Handling",
    riskHarm: "Cuts or lacerations from sharp glass edges, splinters or broken panes.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Handle glass with enough people and correct technique; use cut-resistant gloves or gauntlets; keep edges protected where practical; do not rush handling; stop if glass is unstable. PPE where required: cut-resistant gloves/gauntlets, safety glasses, safety boots, long sleeves.",
    residualRisk: "L",
    reviewTrigger: "Any cut, laceration, splinter injury, damaged edge or unsafe glass handling event.",
    nextReview: "2026-11-25",
    training: "BHT-003 Cutting Glass",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-001B",
    category: "Glass Handling",
    riskHarm: "Eye injury from glass shards, chips or flying particles during cutting, breakage or clean-up.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Wear safety glasses for cutting, breakage response and clean-up; isolate breakage areas; clean shards immediately using suitable tools; dispose of broken glass safely.",
    residualRisk: "L",
    reviewTrigger: "Any eye injury, glass chip/shard event, uncontrolled breakage or clean-up concern.",
    nextReview: "2026-11-25",
    training: "BHT-003 Cutting Glass",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-001C",
    category: "Glass Handling",
    riskHarm: "Crush injury, dropped pane/sash or uncontrolled load movement while lifting or positioning glass.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Plan the lift and route; use enough people; use glass suckers/trolleys where needed; secure/rack glass; keep hands/feet clear of pinch points; stop if load control is lost.",
    residualRisk: "L",
    reviewTrigger: "Any dropped pane/sash, near miss, failed lift plan, sucker issue or load-control event.",
    nextReview: "2026-11-25",
    training: "BHT-002 Manual Handling",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-001D",
    category: "Glass Handling",
    riskHarm: "Manual handling strain while lifting, carrying, loading or controlling glass.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Assess weight and route before lifting; team lift or use mechanical aids; avoid twisting; take breaks; use trolleys/suckers where practical; stop and reassess awkward lifts.",
    residualRisk: "L",
    reviewTrigger: "Any strain, awkward lift, overexertion, loading/unloading issue or manual-handling near miss.",
    nextReview: "2026-11-25",
    training: "BHT-002 Manual Handling",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-002A",
    category: "Working at Height",
    riskHarm: "Fall from ladder due to poor set-up, overreach, damaged ladder or unsuitable access choice.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Choose the safest access method; inspect ladder before use; set on firm level ground; maintain three points of contact; do not overreach; isolate below where needed. When working near overhead power lines or service lines, treat all lines as live; maintain minimum 4m clearance for workers, ladders, EWPs, tools and materials; stop work and escalate if clearance cannot be confirmed or maintained, or if close approach/isolation is required.",
    residualRisk: "L",
    reviewTrigger: "Any ladder near miss, fall risk, damaged ladder, unsafe set-up or ladder misuse; Any work near overhead power lines/service lines, unclear clearance, or close approach/isolation requirement.",
    nextReview: "2026-11-25",
    training: "WAH-001 Ladder Safety",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-002B",
    category: "Working at Height",
    riskHarm: "Fall from scaffold, mobile scaffold or roof edge/opening.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Use competent users; follow scaffold tags and restrictions; do not alter scaffold; manage edges/openings; use barriers/exclusion zones; stop if access is not safe.",
    residualRisk: "L",
    reviewTrigger: "Any scaffold/edge/opening near miss, unauthorised alteration, missing protection or fall-risk event.",
    nextReview: "2026-11-25",
    training: "WAH-002 Mobile Scaffolding",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-002C",
    category: "Working at Height",
    riskHarm: "Electric shock, electrocution or arcing if workers, EWPs, tools or materials enter within 4 metres of overhead power lines, tramway overhead lines or other electrified transport lines.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Use trained/competent operators; complete pre-start checks; follow platform limits and ground conditions; maintain minimum 4m clearance from overhead power lines, tramway overhead lines and other electrified transport lines unless formally approved via close approach consent, isolation or asset-owner control; treat all overhead lines as live; stop work if the 4m clearance cannot be confirmed or maintained; use a spotter where required to maintain safe separation; harness only where required.",
    residualRisk: "L",
    reviewTrigger: "Any EWP/scissor lift defect, misuse, entrapment, tip risk or unsafe ground/overhead condition; Any work near overhead power lines/service lines, unclear clearance, or close approach/isolation requirement.; Any work near tramway overhead lines/electrified transport lines or unclear asset-owner approval requirement.",
    nextReview: "2026-11-25",
    training: "LHE-001 Scissor Lift",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-002D",
    category: "Working at Height",
    riskHarm: "Dropped objects striking people below while work is being done at height.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Isolate below; keep tools/materials secure; do not work above unprotected people; use exclusion zones, toe boards or tool control where practical.",
    residualRisk: "L",
    reviewTrigger: "Any dropped object, falling material, failed exclusion zone or overhead-risk near miss.",
    nextReview: "2026-11-25",
    training: "WAH-001 Ladder Safety",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-003A",
    category: "Site Interaction",
    riskHarm: "Conflict, aggression or assault from occupants, customers, tenants or public.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Confirm site hazards before entry; communicate calmly; do not enter unsafe situations; leave and escalate to supervisor/client/police if threats or violence occur; maintain exit path.",
    residualRisk: "L",
    reviewTrigger: "Any aggression, threat, assault, intimidation or conflict escalation.",
    nextReview: "2026-11-25",
    training: "BHT-004 Site Conduct",
    aroflowGroup: "3. Site Interaction",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-003B",
    category: "Site Interaction",
    riskHarm: "Dog bite or injury from uncontrolled animals on site.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Confirm animals are controlled before entry; do not approach unsecured dogs; ask occupant/client to restrain animals; leave and escalate if animals are uncontrolled.",
    residualRisk: "L",
    reviewTrigger: "Any dog/uncontrolled animal event, bite, near miss or refusal to control animals.",
    nextReview: "2026-11-25",
    training: "BHT-004 Site Conduct",
    aroflowGroup: "3. Site Interaction",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-003C",
    category: "Site Interaction",
    riskHarm: "Exposure to weapons, drugs, needles or unsafe/illegal activity.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Do not touch needles/drugs/weapons; withdraw from the area; secure distance; notify supervisor/client and emergency services where needed; only resume when made safe.",
    residualRisk: "L",
    reviewTrigger: "Any drugs, needles, weapons, threatening item or unsafe/illegal activity discovered.",
    nextReview: "2026-11-25",
    training: "BHT-004 Site Conduct",
    aroflowGroup: "3. Site Interaction",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-003D",
    category: "Site Interaction",
    riskHarm: "Injury to public, customers or occupants from work activity, tools, glass or access restrictions.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Isolate work zones; use cones/barriers/signage; keep public clear of tools, glass and breakage areas; communicate work boundaries; stop if separation cannot be maintained.",
    residualRisk: "L",
    reviewTrigger: "Any public/occupant injury, near miss, breach of exclusion zone or uncontrolled interface.",
    nextReview: "2026-11-25",
    training: "BHT-004 Site Conduct",
    aroflowGroup: "3. Site Interaction",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-003E",
    category: "Site Interaction",
    riskHarm: "Unsafe interaction with other PCBUs or poor communication causing escalation or conflicting work.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Coordinate with site lead/other PCBUs; confirm hazards and work areas; follow site rules; escalate communication issues; stop if simultaneous work creates uncontrolled risk.",
    residualRisk: "L",
    reviewTrigger: "Any PCBU communication failure, conflicting work, site coordination issue or escalation event.",
    nextReview: "2026-11-25",
    training: "BHT-001 Site Safety",
    aroflowGroup: "3. Site Interaction",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-004A",
    category: "Workplace Environment",
    riskHarm: "Slips, trips, rolled ankles or falls from poor housekeeping, uneven ground, hidden potholes in grass, cords, debris, boxes left in walkways, slippery surfaces, muddy or wet accessways.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Plan and check walking routes before moving through office or site areas; use established paths where available; complete site and office access check before work; keep walkways clear; tidy work areas; remove, isolate or mark trip hazards including boxes, cords, debris and potholes; improve lighting/access where practical; use cones/barriers/signage; take extra care on grass, mud, wet or uneven ground; do not rush or carry loads that block vision.",
    residualRisk: "L",
    reviewTrigger: "Any slip, trip, fall on same level, pothole/uneven-ground event, poor housekeeping issue, blocked walkway or wet/muddy access concern.",
    nextReview: "2026-11-25",
    training: "BHT-001 Site Safety",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-004B",
    category: "Workplace Environment",
    riskHarm: "Impact with doors, glass partitions, low head-clearance areas, protruding fittings, leaning timber/materials, furniture, objects, structures or moving site activity.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Plan the walking route and line of travel before moving through offices or sites; check surroundings; keep routes clear; control doors/openings; mark glass partitions, low head-clearance areas and protruding fittings; secure or move leaning timber/materials; maintain separation from moving plant or site activity; mark/isolate impact hazards; slow down at blind corners, doorways and congested areas.",
    residualRisk: "L",
    reviewTrigger: "Any impact, door/glass-partition strike, low-head-clearance event, struck-against incident, unsecured leaning material, blocked route or unexpected moving-site hazard.",
    nextReview: "2026-11-25",
    training: "BHT-001 Site Safety",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-004C",
    category: "Workplace Environment",
    riskHarm: "Puncture wound, cut or minor hand injury to workers, visitors or other people from sharp debris, nails, screws, waste or unexpected site materials.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Inspect work area; remove or isolate sharp debris; wear safety boots and gloves where needed; dispose of waste safely; stop and reassess hidden hazards.",
    residualRisk: "L",
    reviewTrigger: "Any puncture wound, cut, hand injury, sharp debris finding, waste hazard or unexpected site material issue.",
    nextReview: "2026-11-25",
    training: "BHT-001 Site Safety",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-004D",
    category: "Workplace Environment",
    riskHarm: "Restricted access, blocked access/egress or unsafe emergency exit routes caused by materials, boxes, work set-up, vehicles, site layout or temporary works.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Keep access and egress clear; do not block exits, walkways or emergency routes; plan materials/tools storage; keep boxes and stored materials out of travel paths; stop work if safe access or exit cannot be maintained; coordinate with occupants/other PCBUs.",
    residualRisk: "L",
    reviewTrigger: "Any blocked exit, restricted access, walkway obstruction, emergency route issue, poor site layout or unsafe access/egress concern.",
    nextReview: "2026-11-25",
    training: "BHT-001 Site Safety",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-004E",
    category: "Workplace Environment",
    riskHarm: "Unexpected conditions on construction sites creating uncontrolled risk.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Stop and reassess unexpected conditions; isolate or mark hazards; consult supervisor/client/other PCBUs; change method before continuing.",
    residualRisk: "L",
    reviewTrigger: "Any hidden hazard, unexpected construction-site condition or change in site risk that affects safe work.",
    nextReview: "2026-11-25",
    training: "BHT-001 Site Safety",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-004F",
    category: "Workplace Environment",
    riskHarm: "Delayed assistance, escalation or rescue if a worker is injured, threatened, unwell or unable to communicate while working alone.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Avoid lone work for high-risk tasks where practical; confirm job location and check-in/check-out process; keep a charged phone/radio available; assess the site before entry; do not work alone for heavy glass handling, working at height, hazardous substances or unsafe sites; escalate missed check-ins immediately.",
    residualRisk: "L",
    reviewTrigger: "Any missed check-in, loss of contact, injury/illness while alone, after-hours callout concern or lone-working near miss.",
    nextReview: "2026-11-25",
    training: "BHT-001 Site Safety",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-004G",
    category: "Workplace Environment",
    riskHarm: "Office worker injury from walking into doors, door edges, glass panels, furniture or other fixed office fittings.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Maintain good housekeeping; plan/check walking routes; keep walkways, doorways and access routes clear; keep doors fully open or closed where practical; mark glass panels, door edges and protrusions; manage blind corners; keep areas well lit; repair/report damaged fittings; do not rush or carry loads that block vision.",
    residualRisk: "L",
    reviewTrigger: "Any office impact injury, door strike, collision with furniture/fittings, poor visibility issue or repeat near miss in office areas.",
    nextReview: "2026-11-25",
    training: "BHT-001 Site Safety",
    aroflowGroup: "2. Site access & work area",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-005A",
    category: "Vehicles & Glass Transport",
    riskHarm: "Vehicle crash or road incident while travelling for work.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Authorised drivers only; drive to conditions; wear seatbelts; complete pre-start checks; do not drive impaired or distracted; report defects promptly.",
    residualRisk: "L",
    reviewTrigger: "Any vehicle crash, road incident, unsafe driving concern or vehicle defect.",
    nextReview: "2026-11-25",
    training: "VEH-002 Frail Van Operation",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-005B",
    category: "Vehicles & Glass Transport",
    riskHarm: "Pedestrian strike, reversing incident or public traffic interface during parking/loading.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Use safe parking; manage public traffic interface; use spotter/exclusion zone where needed; reverse only when safe; wear high-vis when exposed to traffic.",
    residualRisk: "L",
    reviewTrigger: "Any reversing near miss, pedestrian/public traffic event, unsafe parking or loading-zone issue.",
    nextReview: "2026-11-25",
    training: "VEH-002 Frail Van Operation",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-005C",
    category: "Vehicles & Glass Transport",
    riskHarm: "Load shift, falling glass/tools or failed load restraint during transport.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Secure glass and tools before travel; use racks/restraints correctly; check load before departure and after stops; do not transport unstable loads.",
    residualRisk: "L",
    reviewTrigger: "Any load shift, fallen glass/tools, restraint failure or unstable transport load.",
    nextReview: "2026-11-25",
    training: "VEH-002 Frail Van Operation",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-005D",
    category: "Vehicles & Glass Transport",
    riskHarm: "Broken glass in vehicle causing cuts, exposure or unsafe unloading.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Isolate broken glass; wear suitable PPE; clean and dispose safely; do not continue with loose shards; report and review cause of breakage.",
    residualRisk: "L",
    reviewTrigger: "Any broken-glass-in-van event, shard exposure, unsafe clean-up or transport breakage.",
    nextReview: "2026-11-25",
    training: "BHT-003 Cutting Glass",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-005E",
    category: "Vehicles & Glass Transport",
    riskHarm: "Trailer or frail van failure during use.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Complete vehicle/trailer pre-start checks; inspect racks, tyres, lights, couplings and restraints; tag out faulty equipment; do not use defective transport equipment.",
    residualRisk: "L",
    reviewTrigger: "Any trailer/frail van defect, coupling issue, rack failure or failed pre-start check.",
    nextReview: "2026-11-25",
    training: "VEH-001 Trailer Operation",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-005F",
    category: "Vehicles & Glass Transport",
    riskHarm: "Manual handling strain during loading or unloading of glass/tools.",
    initialRisk: "M",
    controlType: "Minimisation",
    controls: "Plan loading/unloading; use team lifts or handling aids; keep route clear; avoid twisting; stop if load is awkward or unstable.",
    residualRisk: "L",
    reviewTrigger: "Any loading/unloading strain, awkward lift, near miss or manual-handling concern.",
    nextReview: "2026-11-25",
    training: "BHT-002 Manual Handling",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-005G",
    category: "Vehicles & Glass Transport",
    riskHarm: "Unauthorised pedestrian entry into workshop vehicle movement area causing pedestrian strike, crush injury, uncontrolled interaction with vehicles/glass handling or public exposure to workshop hazards.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Restrict workshop access using physical barriers/cordons and clear signage; require all visitors, couriers and delivery drivers to report to reception before entering operational areas; maintain separation between pedestrian access paths and vehicle movement areas; brief visitors/delivery drivers where interaction is required; control entry points to prevent free access; use cones/barriers to reinforce exclusion zones; ensure vehicle operators remain alert to unauthorised pedestrian entry; stop work or isolate the area if separation cannot be maintained.",
    residualRisk: "L",
    reviewTrigger: "Any unauthorised workshop entry, vehicle/pedestrian near miss, delivery/courier entering without reporting, barrier/signage failure or reception-control issue.",
    nextReview: "2026-11-25",
    training: "Site Induction / Vehicle-pedestrian separation awareness",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-006A",
    category: "Plant, Tools & Equipment",
    riskHarm: "Cuts, crush injury or entanglement from plant, tools or machinery.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Use correct equipment; ensure competent users; keep guards in place; keep hands clear of moving parts; do not bypass safety features; wear task-specific PPE.",
    residualRisk: "L",
    reviewTrigger: "Any tool injury, near miss, missing guard, entanglement risk or unsafe use.",
    nextReview: "2026-11-25",
    training: "PTE-002 Power Tools",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-006B",
    category: "Plant, Tools & Equipment",
    riskHarm: "Electric shock from damaged leads, faulty tools or unsuitable electrical equipment.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Complete pre-use checks; use tested/maintained equipment; keep leads protected; tag out faulty gear; do not use damaged electrical tools.",
    residualRisk: "L",
    reviewTrigger: "Any electric shock, damaged lead/tool, failed test/tag or electrical defect.",
    nextReview: "2026-11-25",
    training: "PTE-002 Power Tools",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-006C",
    category: "Plant, Tools & Equipment",
    riskHarm: "Struck-by or dropped-load injury from equipment, lifting aids or failed glass sucker.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Check lifting/handling equipment before use; use within limits; keep people clear of suspended/controlled loads; tag out defective suckers or equipment.",
    residualRisk: "L",
    reviewTrigger: "Any failed sucker, dropped load, lifting aid issue or struck-by near miss.",
    nextReview: "2026-11-25",
    training: "PTE-001 Glass Sucker",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-006D",
    category: "Plant, Tools & Equipment",
    riskHarm: "Equipment failure, defect, unguarded machinery or misuse.",
    initialRisk: "H",
    controlType: "Minimisation",
    controls: "Pre-use checks; maintenance/testing; tag out faulty gear; use correct equipment for the task; no improvised lifting/access methods; supervise inexperienced users.",
    residualRisk: "L",
    reviewTrigger: "Any equipment failure, defect, misuse, unguarded machinery or improvised method.",
    nextReview: "2026-11-25",
    training: "PTE-002 Power Tools",
    aroflowGroup: "1. Glass, tools & transport",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-007A",
    category: "Hazardous Substances",
    riskHarm: "Chemical burns, skin or eye irritation from hazardous substances.",
    initialRisk: "H",
    controlType: "Elimination + Minimisation",
    controls: "Use SDS; label containers; substitute safer products where practical; wear chemical-resistant gloves and eye/face protection where required; wash exposed skin promptly.",
    residualRisk: "L",
    reviewTrigger: "Any chemical burn, skin/eye irritation, splash, SDS change or new substance.",
    nextReview: "2026-11-25",
    training: "CHM-001 SDS Training",
    aroflowGroup: "4. Chemicals, dust & fumes",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-007B",
    category: "Hazardous Substances",
    riskHarm: "Inhalation of fumes, dust or vapour causing illness or respiratory exposure.",
    initialRisk: "H",
    controlType: "Elimination + Minimisation",
    controls: "Use SDS; ventilate; minimise dust/fume generation; use extraction or wet methods where practical; use respirator/RPE if required; stop unknown exposure.",
    residualRisk: "L",
    reviewTrigger: "Any dust/fume/vapour exposure, respiratory concern, RPE requirement or unknown hazardous material.",
    nextReview: "2026-11-25",
    training: "CHM-001 SDS Training",
    aroflowGroup: "4. Chemicals, dust & fumes",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-007C",
    category: "Hazardous Substances",
    riskHarm: "Poisoning or harmful exposure from incorrect use, storage or unlabelled containers.",
    initialRisk: "H",
    controlType: "Elimination + Minimisation",
    controls: "Keep substances labelled; store/segregate correctly; follow SDS; do not use unknown substances; maintain hygiene controls; restrict access where needed.",
    residualRisk: "L",
    reviewTrigger: "Any unlabelled container, incorrect storage/use, poisoning concern or SDS non-compliance.",
    nextReview: "2026-11-25",
    training: "CHM-001 SDS Training",
    aroflowGroup: "4. Chemicals, dust & fumes",
    identified: "2026-06-25",
  },
  {
    hazardId: "CG-HZ-007D",
    category: "Hazardous Substances",
    riskHarm: "Fire, spill exposure or environmental contamination from hazardous substances.",
    initialRisk: "H",
    controlType: "Elimination + Minimisation",
    controls: "Segregate/bund storage; control ignition sources; keep spill kit available; contain and clean spills safely; escalate significant spills; stop work if uncontrolled.",
    residualRisk: "L",
    reviewTrigger: "Any chemical spill, fire risk, storage non-compliance, bunding issue or environmental release.",
    nextReview: "2026-11-25",
    training: "CHM-001 SDS Training",
    aroflowGroup: "4. Chemicals, dust & fumes",
    identified: "2026-06-25",
  },
];
